// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://krrb5dfaenbwfegj7mdz4mrqne.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4dfhiw7r25ejvidnf3rm4nan3a",
    "aws_cognito_identity_pool_id": "eu-west-1:313157a1-d691-40a9-b65d-1e21e79d9996",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_6ZUpaNUB2",
    "aws_user_pools_web_client_id": "4b28l1rs0ol6jm9cn2lo1ui512",
    "oauth": {},
    "aws_user_files_s3_bucket": "suncmsbucket-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
